import type { PaginationQuery } from '../common/pagination';
import type { PaymentMethod } from '../payments/types';

export const INVOICE_STATUSES = [
  'DRAFT',
  'ISSUED',
  'PARTIALLY_PAID',
  'PAID',
  'OVERDUE',
  'VOID',
] as const;
export type InvoiceStatus = (typeof INVOICE_STATUSES)[number];

export type InvoiceSortField = 'createdAt' | 'totalAmount';

export type PaymentSortField = 'paidAt' | 'createdAt';

export interface Invoice {
  id: string;
  childId: string;
  billedToGuardianId: string;
  /** Set only for invoices generated by a BillingRun - null for manually-created invoices. */
  billingRunId: string | null;
  status: InvoiceStatus;
  totalAmount: string;
  dueDate: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface InvoiceLineItem {
  id: string;
  invoiceId: string;
  description: string;
  quantity: string;
  unitAmount: string;
  totalAmount: string;
  createdAt: string;
  updatedAt: string;
}

/** One payment's application to this specific invoice, via PaymentAllocation - amountApplied is this invoice's own portion, not the payment's full amount (a payment can span several invoices). Payment itself is guardian-anchored now - see payments/types.ts. */
export interface InvoicePaymentAllocation {
  id: string;
  paymentId: string;
  amountApplied: string;
  paymentMethod: PaymentMethod;
  paidAt: string;
  createdAt: string;
}

export interface InvoiceQuery extends PaginationQuery {
  childId?: string;
  guardianId?: string;
  /** Invoices generated by a specific BillingRun. */
  billingRunId?: string;
  status?: InvoiceStatus;
  sortBy?: InvoiceSortField;
}

export interface PaymentQuery extends PaginationQuery {
  sortBy?: PaymentSortField;
}

export type LineItemSortField = 'createdAt' | 'totalAmount';

export interface LineItemQuery extends PaginationQuery {
  sortBy?: LineItemSortField;
}

export interface CreateLineItemRequest {
  description: string;
  quantity: number;
  unitAmount: number;
}

export interface CreateInvoiceRequest {
  childId: string;
  billedToGuardianId: string;
  dueDate?: string;
  lineItems?: CreateLineItemRequest[];
}

export interface UpdateInvoiceRequest {
  childId?: string;
  billedToGuardianId?: string;
  dueDate?: string;
}

export type UpdateLineItemRequest = Partial<CreateLineItemRequest>;

export interface IssueInvoiceRequest {
  dueDate?: string;
}

/** Owner Dashboard financial snapshot. from/to only bound invoicedAmount - outstandingAmount/overdueAmount are always as-of-now snapshots. */
export interface InvoiceSummaryQuery {
  from?: string;
  to?: string;
}

export interface InvoiceSummary {
  outstandingAmount: string;
  overdueAmount: string;
  overdueInvoiceCount: number;
  invoicedAmount: string;
}
